### ISSUE TITLE
Unable to use library

### ISSUE THREAD

**Issue by Pika-Boo** [mephux/ruby-nessus#32]
Using the require statement provides the following error

/home/user/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ruby-nessus (LoadError)
	from /home/user/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from nessus.rb:2:in `<main>'

**Comment by JMeyer0101** [comment]
Same issue here.  I have spent a few hours trying to solve the issue with no luck.

**Comment by Hadescho** [comment]
Just expirienced the same issue. The problem most likely is that you've downloaded it from ruby-gems, where the version of the gem still uses the name "nessus". Using:
```ruby
require 'nessus'
```
should do the job for you.
